### ISSUE TITLE
Inconsistent errors when keys are not found

### ISSUE THREAD

**Issue by ed255** [vocdoni/arbo#12]
Arbo sometimes returns `db.ErrKeyNotFound` and other times `arbo.ErrKeyNotFound`.

I think the type `arbo.ErrKeyNotFound` should be removed and internally use `db.ErrKeyNotFound`.  Unless I'm missing something and these two errors have different meanings?

**Comment by arnaucube** [comment]
Yes, they have different meanings:
- `arbo.ErrKeyNotFound` means that the key was not found in the MerkleTree at the expected path under the Root
- `db.ErrKeyNotFound` means that was expecting to find a key in the key-value db and was not found

Maybe can be abstracted in a way that the user of the library does not need to handle two similar but different errors.

**Comment by ed255** [comment]
@arnaucube I consider this issue resolved after the fix https://github.com/vocdoni/arbo/pull/14

I don't think further changes are required.  As I see it `arbo.ErrKeyNotFound` is an expected error that the user of the library may be interested in handling, and `db.ErrKeyNotFound` is an unexpected error caused by either a bug or a database failure which the user of the library can't handle.

I think this can be closed!

**Comment by arnaucube** [comment]
Perfect
