### ISSUE TITLE
Snapshot returns a writable tree, which allows forking and losing current tree

### ISSUE THREAD

**Issue by ed255** [vocdoni/arbo#5]
`Snapshot` will be renamed to `FromRoot`
`FromRoot` will return a read-only Tree to avoid creating forks.

**Comment by arnaucube** [comment]
Updated this in https://github.com/vocdoni/arbo/commit/f47d4abedc5ba3658df6f22349c1ccc4b4dc6cfc , and now Snapshot is a read-only view of the tree and does not allow to fork trees.
But for the moment did not changed the name from `Snapshot` to `FromRoot`, as I think that `FromRoot` would not be as clear as `Snapshot` (and in the `Snapshot` method the input parameter is 'fromRoot', which makes it clear how the method is used.
